### PR TITLE
Config with default template (dependencies)

### PR DESCRIPTION
**Pull request by gforcada**
Update configuration with https://github.com/plone/meta/pull/34

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@mauritsvanrees interesting here, by defining that it has a testing dependency on `ZServer` that fails on jenkins.

Looking into it, indeed there are `ZServer` imports, though conditional.

IMHO we could remove the tests and code that still depend on `ZServer`, `plone.subrequest` is python 3 only and is not used (master branch) on Plone 5.2, so there is no setup that puts together `plone.subrequest` (master branch) and `ZServer`.

I am adding a commit removing that.

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM.
I agree that the ZServer related test code can be removed.

**Pull request merged**
